# Uncomment this line to define a global platform for your project
platform :ios, '8.0'      #Incorpored Swift so it's 8+

target 'Que Hacer MDQ v2' do
pod 'AFNetworking', '~> 2.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'M13InfiniteTabBar', '~> 2.3'
pod 'MMDrawerController', '~> 0.5.5'

end

